In [1]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn import datasets

np.random.seed(5)

iris = datasets.load_iris()
Features = iris.data
target_ids = iris.target #label

In [2]:
## Hàm tính khoảng cách Euclid
def Euclid_dist(x,y):
    Dist= np.sqrt(sum(np.square((x-y))))
    return Dist

In [3]:
### Chia ngẫu nhiên tập dữ liệu thành training và test.
### Bằng cách chọn ngẫu nhiên các hàng-ID làm training và testing
arr = np.arange(150)### data có 150 hàng
np.random.shuffle(arr)## Làm ngẫu nhiên các hàng-ID
##Chọn 90 số hàng ID làm training và 60 hàng-ID làm testing
Training = Features[arr[0:90],:]
Training_label = target_ids[arr[0:90]]
Testing = Features[arr[90:150],:]
Testing_label = target_ids[arr[90:150]]

In [4]:
Training

array([[5.8, 2.7, 3.9, 1.2],
       [6.1, 2.6, 5.6, 1.4],
       [5.8, 2.8, 5.1, 2.4],
       [4.4, 3.2, 1.3, 0.2],
       [7.2, 3.6, 6.1, 2.5],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 3. , 1.4, 0.2],
       [5.9, 3.2, 4.8, 1.8],
       [5. , 3. , 1.6, 0.2],
       [5.4, 3. , 4.5, 1.5],
       [5.6, 3. , 4.5, 1.5],
       [6.3, 2.8, 5.1, 1.5],
       [7.1, 3. , 5.9, 2.1],
       [7.3, 2.9, 6.3, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [5.1, 3.3, 1.7, 0.5],
       [6.3, 2.7, 4.9, 1.8],
       [7.4, 2.8, 6.1, 1.9],
       [5.1, 3.7, 1.5, 0.4],
       [4.8, 3. , 1.4, 0.1],
       [6.1, 2.8, 4. , 1.3],
       [6.4, 2.8, 5.6, 2.1],
       [5.3, 3.7, 1.5, 0.2],
       [6.3, 2.5, 4.9, 1.5],
       [5.6, 3. , 4.1, 1.3],
       [6.2, 3.4, 5.4, 2.3],
       [6.4, 2.9, 4.3, 1.3],
       [5.7, 2.9, 4.2, 1.3],
       [6.1, 2.9, 4.7, 1.4],
       [6.4, 2.8, 5.6, 2.2],
       [5.1, 3.4, 1.5, 0.2],
       [5.5, 2.3, 4. , 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.4, 3.7, 1.5, 0.2],
       [7. , 3

In [5]:
Training_label

array([1, 2, 2, 0, 2, 1, 0, 1, 0, 1, 1, 2, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 1, 0, 0, 2, 0, 2, 2, 1, 0, 0,
       1, 2, 1, 2, 2, 0, 2, 0, 0, 0, 0, 1, 1, 1, 1, 2, 1, 2, 2, 1, 0, 1,
       0, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 0, 2, 0, 0, 1, 0, 0, 2, 1, 0,
       2, 0])

In [6]:
Testing

array([[6. , 2.2, 5. , 1.5],
       [5.5, 2.6, 4.4, 1.2],
       [5.8, 4. , 1.2, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [6.4, 2.7, 5.3, 1.9],
       [6. , 3.4, 4.5, 1.6],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 4.2, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.1, 3. , 4.6, 1.4],
       [4.6, 3.1, 1.5, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 4.1, 1. ],
       [4.8, 3.4, 1.6, 0.2],
       [6. , 2.2, 4. , 1. ],
       [6.4, 3.1, 5.5, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [6.3, 3.3, 6. , 2.5],
       [6.8, 3.2, 5.9, 2.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [6. , 2.7, 5.1, 1.6],
       [7.7, 2.8, 6.7, 2. ],
       [4.4, 3. , 1.3, 0.2],
       [6.2, 2.2, 4.5, 1.5],
       [4.7, 3.2, 1.3, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [6.7, 3.1, 5.6, 2.4],
       [6.4, 3.2, 4.5, 1.5],
       [7.6, 3. , 6.6, 2.1],
       [5.5, 3.5, 1.3, 0.2],
       [6.5, 3

In [7]:
Testing_label

array([2, 1, 0, 0, 2, 1, 1, 0, 0, 2, 1, 1, 0, 1, 2, 1, 0, 1, 2, 2, 2, 2,
       0, 0, 1, 2, 0, 1, 0, 0, 2, 1, 2, 0, 2, 0, 2, 0, 1, 0, 2, 2, 0, 2,
       2, 2, 1, 0, 1, 0, 0, 1, 2, 0, 2, 0, 1, 2, 2, 1])

In [9]:
x= Testing[0]
L= np.shape(Training)[0]
D= np.zeros(L)
for i in range(0,L):
   D[i]= Euclid_dist(x, Training[i,0:4]) 

In [11]:
index = np.argsort(D)

In [12]:
index

array([23, 50, 16, 11, 40, 79, 73, 45,  1, 28, 59, 72, 44, 77, 10, 55, 71,
        7, 67, 61, 26,  2, 88, 21,  9, 27, 46, 74, 31, 65, 29, 56, 20, 75,
        0, 41, 63, 24, 68, 39, 62, 34, 82, 76, 57, 25, 47, 69, 70, 32, 12,
       60, 17, 13, 86,  5, 58, 37,  4, 85, 48, 15, 81, 49,  8, 36, 14, 84,
       30, 89, 83,  6, 18, 33, 43, 22, 54, 35, 42, 19, 87, 52, 38, 66, 51,
       53, 78,  3, 80, 64])

In [14]:
ListID= Training_label[index[0:5]]

In [15]:
ID= np.argmax(np.histogram(ListID,bins=[0, 1, 2,3])[0])

In [16]:
ID

2

In [17]:
Testing_label[0]

2

In [19]:
### Viết hàm gán ID cho từng phần tử x
### x: testing_data, bỏ qua trường ID cuối cùng
### Training: dữ liệu training,
### Training_label: id của data training 
###K: số hàng xóm, trong thuật toán K-NN
def Gan_ID(x, Training,Training_label,K):
    L= np.shape(Training)[0]
    D= np.zeros(L)
    for i in range(0,L):
       D[i]= Euclid_dist(x, Training[i,0:4]) 
    index = np.argsort(D)
    ListID= Training_label[index[0:K]]
    ID= np.argmax(np.histogram(ListID,bins=[0, 1, 2,3])[0])
    return ID

In [22]:
Testing_label[1]

1

In [21]:
Gan_ID(Testing[1,0:4],Training,Training_label,9)

1

In [ ]:
import numpy as np

In [30]:
def dist_l2(x,y):
# Khoang cach 2 vectors:    
    return np.sqrt(sum((x-y)**2))

In [29]:
def Most_freq_matrix(V):
    ##V: matrix
    ## return the most frequent item of v
    temps=sorted(set(V.reshape(-1,)))
    most_freq=[]
    for i in range(0,np.shape(V)[0]):
        v=V[i,:]
        item_freq=[]
         # tao ra 1 list cac item co thu tu 
        for item in temps:
            item_freq.append(list(v).count(item))
        most_freq.append(temps[np.argmax(item_freq)])
    
    return np.array(most_freq)

In [28]:
def Most_freq(v):
    ##v: np.array
    ## return the most frequent item of v
    item_freq=[]
    temps=sorted(set(v)) # tao ra 1 list cac item co thu tu 
    for item in temps:
        item_freq.append(list(v).count(item))
    most_freq=temps[np.argmax(item_freq)]
    return most_freq

In [33]:
def KNN_1(Training, Training_label, Testing, Testing_label):
    Number_test= np.shape(Testing)[0]
    Number_training = np.shape(Training)[0]    
    Distmatrix=np.zeros([Number_test,Number_training])
    Id_testx=[]
    for i  in range(0,Number_test):
        for j in range(0,Number_training):
            Distmatrix[i,j] = dist_l2(Testing[i,:] ,Training[j,:])
#Distmatrix[i,:]: khoang cach tu test i den tat ca cac training
    for K in [1,3,5,7,9,11,13,15,17,20]:
        Id_testx=[]
        for i  in range(0,Number_test):
            closest_training= np.argsort(Distmatrix[i,:])[0:K]
            top_k_labels=Training_label[closest_training] 
        ## Label cua K anh training giong anh test_x nhat
            Id_testx.append(Most_freq(top_k_labels))

        Id_testx= np.array(Id_testx)   
        Accuracy=sum(Id_testx==Testing_label)/len(Testing_label)

        print("with K=",K,"Accuracy=", Accuracy)  
    return 

In [34]:
KNN_1(Training, Training_label, Testing, Testing_label)

with K= 1 Accuracy= 0.95
with K= 3 Accuracy= 0.9666666666666667
with K= 5 Accuracy= 0.9666666666666667
with K= 7 Accuracy= 0.9666666666666667
with K= 9 Accuracy= 0.9666666666666667
with K= 11 Accuracy= 0.9666666666666667
with K= 13 Accuracy= 0.9666666666666667
with K= 15 Accuracy= 0.9666666666666667
with K= 17 Accuracy= 0.9666666666666667
with K= 20 Accuracy= 0.9333333333333333
